export { default as DataTablePage } from './DataTablePage'
export { default as InputPage } from './InputPage'
export { default as SelectPage } from './SelectPage'
export { default as DefaultPage } from './DefaultPage'
export { default as ErrorPage } from './ErrorPage'